# Generated by Django 3.0.4 on 2020-05-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_musician_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='num_stars',
            field=models.IntegerField(null=True),
        ),
    ]
